AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 Existing Bucket Integration

Globals:
  Function:
    Timeout: 30

Resources:

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: s3-folder-trigger-function
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64

      Policies:
        - S3ReadPolicy:
            BucketName: sreenath-v1

      Events:
        S3UploadEvent:
          Type: S3
          Properties:
            Bucket: sreenath-v1
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: raw_data/
                  - Name: suffix
                    Value: .csv